import { ICartItem } from "../@types/cart";
import {
  IFilterFieldRange,
  IFilterFieldsRangesResponse,
} from "../@types/catalog";
import {
  ICategory,
  ICategoryFlatItem,
  ICategoryItem,
} from "../@types/category";
import { IPagination } from "../@types/common";
import { IDetailedOrder, IOrder } from "../@types/order";
import { ICartProduct, IProduct, IProductItem } from "../@types/product";
import {
  IBasicSettings,
  ICheckoutPageSettings,
  ISystemTax,
  TCalculateTaxBasedOn,
} from "../@types/settings";
import { ICall2OrderData } from "../redux/reducers/cart";
import { ITotal } from "../@types/total";
import { ICheckoutStepper } from "../@types/checkout";
import { ICheckoutShippingPageData } from "../@types/delivery";
import { ICheckoutPaymentPageData } from "../@types/payment";

export const basicSettings: IBasicSettings = {
  "system.locale": {
    phone: { mask: null, placeholder: "+1(555)123-4567" },
    money: {
      decimal: ".",
      thousand: ",",
      precision: 2,
      format: "%v %s",
      symbol: "$",
    },
    date: {
      dateShort: "MM/dd/yy",
      dateMedium: "dd-MMM-yyyy",
      dateLong: "MMMM d, yyyy",
      dateTimeShort: "MM/dd/yy HH:mm",
      dateTimeMedium: "dd-MMM-yyyy HH:mm",
      dateTimeLong: "MMMM d, yyyy HH:mm",
      time: "HH:mm",
    },
  },
  "system.currency": {
    currency_id: 4,
    alias: "usd",
    code: 840,
    title: "US Dollar",
  },
};

export const categoryTree: ICategory[] = [
  {
    category_id: 99,
    parent_id: null,
    title: "iPhone cases",
    url_key: "chekhly-na-iphone",
    tree_sort: "00000000",
    level: 0,
    image: null,
    custom_link: null,
    children: [
      {
        category_id: 103,
        parent_id: 99,
        title: "iPhone 7",
        url_key: "iphone-7",
        tree_sort: "00000000.00000001",
        level: 1,
        image: null,
        custom_link: null,
      },
      {
        category_id: 104,
        parent_id: 99,
        title: "iPhone 7 Plus",
        url_key: "iphone-7-plus",
        tree_sort: "00000000.00000002",
        level: 1,
        image: null,
        custom_link: null,
      },
      {
        category_id: 105,
        parent_id: 99,
        title: "iPhone 6",
        url_key: "iphone-6",
        tree_sort: "00000000.00000003",
        level: 1,
        image: null,
        custom_link: null,
      },
      {
        category_id: 106,
        parent_id: 99,
        title: "iPhone 5/5s",
        url_key: "iphone-5-5s",
        tree_sort: "00000000.00000004",
        level: 1,
        image: null,
        custom_link: null,
      },
    ],
  },
];

export const products: IProduct[] = [
  {
    product_id: 165,
    sku: "iphone-case-explorer-wanted",
    title: "Case Explorer wanted",
    url_key: "chekhol-explorer-wanted",
    has_variants: true,
    external_id: null,
    item_id: 3595,
    in_stock: true,
    prices: [
      {
        price_id: 7,
        value: null,
        min: "8.99",
        max: "8.99",
        old: null,
        old_min: "12.00",
        old_max: "12.00",
        price_alias: "selling_price",
        currency_alias: "rub",
      },
    ],
    text: {
      description:
        "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a posuere arcu, vitae dignissim tortor. Aliquam pharetra luctus ultrices. Suspendisse vitae dui nibh. Nam maximus tristique dolor, at porta ante gravida quis. Cras vehicula at arcu sit amet vestibulum. Aliquam vel felis viverra, mollis elit in, mollis ligula. Quisque convallis dui nec molestie bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla rhoncus felis id suscipit venenatis. Duis eget accumsan massa, vel dictum ante.</p>",
      custom_title: null,
      meta_description: null,
    },
    props: {
      available_qty: 40,
      reserved_qty: 0,
      country_of_origin: null,
      extra: null,
      size: { weight: 0.1 },
      attr_values: {
        for_iphone: [615],
        type_of_case: [605],
        film_is_included: [610],
        is_charging_case: [603],
      },
      tax_status: "taxable",
      tax_class_id: null,
      arbitrary_data: null,
    },
    manufacturer: {
      manufacturer_id: 34,
      title: "Anymode",
      url_key: "anymode",
      image:
        "https://images.unsplash.com/photo-1736210811075-7509d5023a4a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    default_category: {
      category_id: 103,
      title: "iPhone 7",
      url_key: "iphone-7",
    },
    images: [
      {
        image_id: 232,
        path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1501,
        height: 1501,
        is_default: true,
        description: null,
        alt: null,
        tags: null,
      },
      {
        image_id: 233,
        path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1051,
        height: 1051,
        is_default: false,
        description: null,
        alt: null,
        tags: null,
      },
    ],
    product_type: {
      group_id: 61,
      title: "Default Product type",
      is_default: true,
      physical_products: true,
      track_inventory: false,
    },
    labels: [
      {
        label_id: 4,
        title: "Best choice",
        color: "#0e8a16",
        text_color: "#000000",
        icon: null,
      },
    ],
    status: "published",
    deleted_at: null,
    sort_price: "8.99",
    sort_in_stock: 1,
  },
];

export const pagination: IPagination = {
  currentPage: 1,
  pageCount: 2,
  perPage: 12,
  totalCount: 16,
};

export const category: ICategoryItem = {
  category_id: 99,
  title: "iPhone cases",
  url_key: "chekhly-na-iphone",
  parent_id: null,
  external_id: null,
  products_qty: 16,
  text: {
    custom_title: null,
    meta_description: null,
    description_top: null,
    description_bottom: null,
  },
  props: {
    use_filter: true,
    filter_id: null,
    custom_link: null,
    arbitrary_data: null,
  },
  children: [
    {
      category_id: 103,
      level: 1,
      tree_sort: "00000000.00000001",
      joined_title: "iPhone cases/iPhone 7",
      title: "iPhone 7",
      url_key: "iphone-7",
      parent_id: 99,
      image: null,
      custom_link: null,
      products_qty: 13,
      children_qty: 0,
    },
  ],
  siblings: [
    {
      category_id: 99,
      level: 0,
      tree_sort: "00000000",
      joined_title: "iPhone cases",
      title: "iPhone cases",
      url_key: "chekhly-na-iphone",
      parent_id: null,
      image: null,
      custom_link: null,
      products_qty: 16,
      children_qty: 4,
    },
  ],
  parents: [
    {
      category_id: 99,
      parent_id: null,
      lang_id: 1,
      title: "iPhone cases",
      url_key: "chekhly-na-iphone",
      tree_sort: "00000000",
      level: 0,
      deleted_at: null,
      custom_link: null,
      status: "published",
      image_id: null,
    },
  ],
  filter: {
    filter_id: 9,
    title: "Filter set for phone cases",
    is_default: true,
    created_at: "2017-04-24 08:40:51.334168-04",
    fields: [
      {
        field_id: 45,
        filter_id: 9,
        type: "price",
        characteristic_id: null,
        sort: 10,
      },
    ],
  },
  seo: {
    compiledTitle: "iPhone cases - buy online with free shipping",
    compiledMetaDescription:
      "Check out our iPhone cases for the best prices. Worldwide shipping.",
    customTitle: null,
    customMetaDesc: null,
    title: "iPhone cases - buy online with free shipping",
    metaDesc:
      "Check out our iPhone cases for the best prices. Worldwide shipping.",
  },
  status: "published",
  created_by: null,
  created_at: "2017-04-22 12:20:49.144755-04",
  deleted_at: null,
  sort: 0,
};

export const product: IProductItem = {
  product_id: 165,
  sku: "iphone-case-explorer-wanted",
  title: "Case Explorer wanted",
  url_key: "chekhol-explorer-wanted",
  has_variants: true,
  external_id: null,
  item_id: 3595,
  in_stock: true,
  prices: [
    {
      price_id: 7,
      value: null,
      min: "8.99",
      max: "8.99",
      old: null,
      old_min: "12.00",
      old_max: "12.00",
      price_alias: "selling_price",
      currency_alias: "rub",
    },
  ],
  text: {
    description:
      "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a posuere arcu, vitae dignissim tortor. Aliquam pharetra luctus ultrices. Suspendisse vitae dui nibh. Nam maximus tristique dolor, at porta ante gravida quis. Cras vehicula at arcu sit amet vestibulum. Aliquam vel felis viverra, mollis elit in, mollis ligula. Quisque convallis dui nec molestie bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla rhoncus felis id suscipit venenatis. Duis eget accumsan massa, vel dictum ante.</p>",
    custom_title: null,
    meta_description: null,
  },
  images: [
    {
      product_image_id: 140,
      is_default: false,
      sort: 0,
      description: null,
      alt: null,
      image: {
        image_id: 232,
        name: "764aacdf5744e92ea6bd0ae94100c711.jpeg",
        size: 189427,
        path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1051,
        height: 1051,
        used_in: ["product"],
        created_at: "2017-04-24 04:02:34.028832-04",
        mime_type: "image/jpeg",
      },
      tags: null,
    },
    {
      product_image_id: 141,
      is_default: true,
      sort: 10,
      description: null,
      alt: null,
      image: {
        image_id: 233,
        name: "d92a4288c09fd1736a3c5c8e17edbc14.jpeg",
        size: 589437,
        path: "https://plus.unsplash.com/premium_photo-1733306523150-77b7bc4e22db?q=80&w=2067&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1501,
        height: 1501,
        used_in: ["product"],
        created_at: "2017-04-24 04:02:34.254748-04",
        mime_type: "image/jpeg",
      },
      tags: null,
    },
  ],
  props: {
    available_qty: 40,
    reserved_qty: 0,
    country_of_origin: null,
    extra: null,
    size: {
      weight: 0.1,
    },
    tax_status: "taxable",
    tax_class_id: null,
    arbitrary_data: null,
    attr_values: {
      for_iphone: [615],
      type_of_case: [605],
      film_is_included: [610],
      is_charging_case: [603],
    },
  },
  manufacturer: {
    manufacturer_id: 34,
    title: "Anymode",
    url_key: "anymode",
    text: {
      custom_title: null,
      meta_description: null,
      description: null,
    },
    image: {
      image_id: 209,
      name: "anymode_large.jpeg",
      size: 15092,
      path: "https://images.unsplash.com/photo-1736210811075-7509d5023a4a?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      width: 480,
      height: 172,
      used_in: ["manufacturer"],
      created_at: "2017-04-23 06:06:56.761346-04",
      mime_type: "image/jpeg",
    },
    status: "published",
    created_by: null,
    created_at: "2017-04-23 06:06:48.607627-04",
  },
  categoryRels: [
    {
      is_default: true,
      category: {
        category_id: 103,
        title: "iPhone 7",
        url_key: "iphone-7",
        parent_id: 99,
        external_id: null,
        text: {
          custom_title: "Чехлы для iPhone 7",
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:21:42.979039-04",
        deleted_at: null,
        sort: 1,
      },
    },
    {
      is_default: false,
      category: {
        category_id: 104,
        title: "iPhone 7 Plus",
        url_key: "iphone-7-plus",
        parent_id: 99,
        external_id: null,
        text: {
          custom_title: "Чехлы для iPhone 7 Plus",
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:21:51.284754-04",
        deleted_at: null,
        sort: 2,
      },
    },
    {
      is_default: false,
      category: {
        category_id: 105,
        title: "iPhone 6",
        url_key: "iphone-6",
        parent_id: 99,
        external_id: null,
        text: {
          custom_title: "Чехлы для iPhone 6",
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:21:59.150955-04",
        deleted_at: null,
        sort: 3,
      },
    },
    {
      is_default: false,
      category: {
        category_id: 106,
        title: "iPhone 5/5s",
        url_key: "iphone-5-5s",
        parent_id: 99,
        external_id: null,
        text: {
          custom_title: "Чехлы для iPhone 5/5s",
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:22:27.62925-04",
        deleted_at: null,
        sort: 4,
      },
    },
    {
      is_default: false,
      category: {
        category_id: 110,
        title: "With picture",
        url_key: "s-risunkom",
        parent_id: 107,
        external_id: null,
        text: {
          custom_title: "Чехлы с рисунком",
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:30:26.133662-04",
        deleted_at: null,
        sort: 3,
      },
    },
    {
      is_default: false,
      category: {
        category_id: 107,
        title: "Collections",
        url_key: "podborki",
        parent_id: null,
        external_id: null,
        text: {
          custom_title: "Подборки чехлов",
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:29:18.181863-04",
        deleted_at: null,
        sort: 30,
      },
    },
    {
      is_default: false,
      category: {
        category_id: 99,
        title: "iPhone cases",
        url_key: "chekhly-na-iphone",
        parent_id: null,
        external_id: null,
        text: {
          custom_title: null,
          meta_description: null,
          description_top: null,
          description_bottom: null,
        },
        props: {
          use_filter: true,
          filter_id: null,
          custom_link: null,
          arbitrary_data: null,
        },
        status: "published",
        created_by: null,
        created_at: "2017-04-22 12:20:49.144755-04",
        deleted_at: null,
        sort: 0,
      },
    },
  ],
  default_category: {
    category_id: 103,
    title: "iPhone 7",
    url_key: "iphone-7",
    parent_id: 99,
    external_id: null,
    text: {
      custom_title: "Чехлы для iPhone 7",
      meta_description: null,
      description_top: null,
      description_bottom: null,
    },
    status: "published",
    created_by: null,
    created_at: "2017-04-22 12:21:42.979039-04",
    deleted_at: null,
    sort: 1,
  },
  product_type: {
    group_id: 61,
    is_default: true,
    physical_products: true,
    title: "Default Product type",
    track_inventory: false,
  },
  labels: [
    {
      label_id: 4,
      color: "#0e8a16",
      text_color: "#000000",
      icon: null,
      remove_after: null,
      created_at: "2017-04-24 08:57:58.125999-04",
      deleted_at: null,
      title: "Best choice",
    },
  ],
  extendedVariants: {
    list: [
      {
        variant_id: 1248,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 7",
        cases: [612],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 7",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3596,
          product_id: null,
          variant_id: 1248,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
      {
        variant_id: 1249,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 7 plus",
        cases: [613],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 7 plus",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3597,
          product_id: null,
          variant_id: 1249,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
      {
        variant_id: 1250,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 6",
        cases: [614],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 6",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3598,
          product_id: null,
          variant_id: 1250,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
      {
        variant_id: 1251,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 5/5s",
        cases: [615],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 5/5s",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3599,
          product_id: null,
          variant_id: 1251,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
    ],
    characteristics: [
      {
        id: 152158,
        title: "For iphone",
        cases: [
          {
            id: 612,
            title: "iPhone 7",
          },
          {
            id: 613,
            title: "iPhone 7 plus",
          },
          {
            id: 614,
            title: "iPhone 6",
          },
          {
            id: 615,
            title: "iPhone 5/5s",
          },
        ],
      },
    ],
    combinations: {
      "1248": ["152158-612"],
      "1249": ["152158-613"],
      "1250": ["152158-614"],
      "1251": ["152158-615"],
    },
    idCombinations: {
      "1248": {
        "152158": 612,
      },
      "1249": {
        "152158": 613,
      },
      "1250": {
        "152158": 614,
      },
      "1251": {
        "152158": 615,
      },
    },
  },
  attributes: [
    {
      id: 152157,
      title: "Case characteristics",
      is_folder: true,
      children: [
        {
          id: 152154,
          title: "Is Charging Case?",
          alias: "is_charging_case",
          type: "radio",
          cases: [
            {
              id: 603,
              title: "No",
            },
          ],
        },
        {
          id: 152155,
          title: "Type of case",
          alias: "type_of_case",
          type: "radio",
          cases: [
            {
              id: 605,
              title: "Clip case",
            },
          ],
        },
        {
          id: 152156,
          title: "Film is included",
          alias: "film_is_included",
          type: "radio",
          cases: [
            {
              id: 610,
              title: "No",
            },
          ],
        },
      ],
    },
  ],
  seo: {
    compiledTitle: "Buy a cheap Case Explorer wanted. Fast worldwide shipping!",
    compiledMetaDescription:
      "Buy Case Explorer wanted, iphone-case-explorer-wanted, from usd 8.99 Fast worldwide shipping!Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a posuere arcu, vitae dignissim tor...",
    customTitle: null,
    customMetaDesc: null,
    title: "Buy a cheap Case Explorer wanted. Fast worldwide shipping!",
    metaDesc:
      "Buy Case Explorer wanted, iphone-case-explorer-wanted, from usd 8.99 Fast worldwide shipping!Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a posuere arcu, vitae dignissim tor...",
  },
  status: "published",
  created_by: null,
  created_at: "2017-04-24 04:02:23.326909-04",
  deleted_at: null,
};

export const selectedVariantData: ICartProduct = {
  product_id: 165,
  sku: "iphone-case-explorer-wanted",
  title: "Case Explorer wanted",
  url_key: "chekhol-explorer-wanted",
  has_variants: true,
  external_id: null,
  item_id: 3595,
  in_stock: true,
  prices: [
    {
      price_id: 7,
      value: null,
      min: "8.99",
      max: "8.99",
      old: null,
      old_min: "12.00",
      old_max: "12.00",
      price_alias: "selling_price",
      currency_alias: "rub",
    },
  ],
  text: {
    description:
      "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a posuere arcu, vitae dignissim tortor. Aliquam pharetra luctus ultrices. Suspendisse vitae dui nibh. Nam maximus tristique dolor, at porta ante gravida quis. Cras vehicula at arcu sit amet vestibulum. Aliquam vel felis viverra, mollis elit in, mollis ligula. Quisque convallis dui nec molestie bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla rhoncus felis id suscipit venenatis. Duis eget accumsan massa, vel dictum ante.</p>",
    custom_title: null,
    meta_description: null,
  },
  images: [
    {
      product_image_id: 140,
      is_default: false,
      sort: 0,
      description: null,
      alt: null,
      image: {
        image_id: 232,
        name: "764aacdf5744e92ea6bd0ae94100c711.jpeg",
        size: 189427,
        path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1051,
        height: 1051,
        used_in: ["product"],
        created_at: "2017-04-24 04:02:34.028832-04",
        mime_type: "image/jpeg",
      },
      tags: null,
    },
    {
      product_image_id: 141,
      is_default: true,
      sort: 10,
      description: null,
      alt: null,
      image: {
        image_id: 233,
        name: "d92a4288c09fd1736a3c5c8e17edbc14.jpeg",
        size: 589437,
        path: "https://plus.unsplash.com/premium_photo-1733306523150-77b7bc4e22db?q=80&w=2067&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1501,
        height: 1501,
        used_in: ["product"],
        created_at: "2017-04-24 04:02:34.254748-04",
        mime_type: "image/jpeg",
      },
      tags: null,
    },
  ],
  props: {
    available_qty: 40,
    reserved_qty: 0,
    country_of_origin: null,
    extra: null,
    size: {
      weight: 0.1,
    },
    tax_status: "taxable",
    tax_class_id: null,
    arbitrary_data: null,
    attr_values: {
      for_iphone: [615],
      type_of_case: [605],
      film_is_included: [610],
      is_charging_case: [603],
    },
  },
  extendedVariants: {
    list: [
      {
        variant_id: 1248,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 7",
        cases: [612],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 7",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3596,
          product_id: null,
          variant_id: 1248,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
      {
        variant_id: 1249,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 7 plus",
        cases: [613],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 7 plus",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3597,
          product_id: null,
          variant_id: 1249,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
      {
        variant_id: 1250,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 6",
        cases: [614],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 6",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3598,
          product_id: null,
          variant_id: 1250,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
      {
        variant_id: 1251,
        product_id: 165,
        sku: "iphone-case-explorer-wanted-iPhone 5/5s",
        cases: [615],
        created_at: "2017-04-24 04:03:19.267605-04",
        size: [],
        title: "iPhone 5/5s",
        prices: [
          {
            price_id: 7,
            value: "8.99",
            min: null,
            max: null,
            old: "12.00",
            old_min: null,
            old_max: null,
            price_alias: "selling_price",
            currency_alias: "usd",
          },
        ],
        in_stock: true,
        inventoryItem: {
          item_id: 3599,
          product_id: null,
          variant_id: 1251,
          available_qty: 10,
          reserved_qty: 0,
          custom_item_id: null,
        },
        images: [],
      },
    ],
    characteristics: [
      {
        id: 152158,
        title: "For iphone",
        cases: [
          {
            id: 612,
            title: "iPhone 7",
          },
          {
            id: 613,
            title: "iPhone 7 plus",
          },
          {
            id: 614,
            title: "iPhone 6",
          },
          {
            id: 615,
            title: "iPhone 5/5s",
          },
        ],
      },
    ],
    combinations: {
      "1248": ["152158-612"],
      "1249": ["152158-613"],
      "1250": ["152158-614"],
      "1251": ["152158-615"],
    },
    idCombinations: {
      "1248": {
        "152158": 612,
      },
      "1249": {
        "152158": 613,
      },
      "1250": {
        "152158": 614,
      },
      "1251": {
        "152158": 615,
      },
    },
  },
  status: "published",
  created_by: null,
  created_at: "2017-04-24 04:02:23.326909-04",
  deleted_at: null,
};

export const addedCallOrderData: ICall2OrderData = {
  item: {
    item_id: 3596,
    type: "variant",
    track_inventory: false,
    available_qty: 10,
    reserved_qty: 0,
    product_id: 165,
    variant_id: 1248,
    custom_item_id: null,
    status: "published",
    deleted_at: null,
    product: {
      product_id: 165,
      sku: "iphone-case-explorer-wanted",
      has_variants: true,
      title: "Case Explorer wanted",
      url_key: "chekhol-explorer-wanted",
      default_category_id: 103,
      manufacturer_id: 34,
      tax_status: "taxable",
      tax_class_id: null,
    },
    variant: {
      variant_id: 1248,
      sku: "iphone-case-explorer-wanted-iPhone 7",
      title: "iPhone 7",
      cases: [612],
      size: [],
    },
    commodity_group: {
      group_id: 61,
      physical_products: true,
      title: "Default Product type",
      trackInventory: false,
    },
    image: {
      path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      width: 1501,
      height: 1501,
    },
    prices: [
      {
        point_id: 1,
        price_id: 7,
        alias: "selling_price",
        currency_id: 4,
        currency_alias: "usd",
        value: 8.99,
        min: null,
        max: null,
        is_auto_generated: true,
        old: 12,
        old_min: null,
        old_max: null,
      },
    ],
  },
  qty: 1,
  price: {
    final_price: 8.99,
    basic_price: 12,
    price_id: 7,
    discount_amount: "3.01",
  },
};

export const cartTotalData = {
  id: "d6872561-b339-4c4c-b452-f30024b3f9fa",
  created_at: "2025-01-17 08:22:07.616021-05",
  total: {
    qty: 1,
    total: "8.99",
  },
};

export const cartData: ICartItem[] = [
  {
    basket_item_id: 546,
    item_id: 3599,
    qty: 1,
    item_price_id: 599,
    created_at: "2025-01-20 14:45:48.229802-05",
    itemPrice: {
      item_price_id: 599,
      price_id: 7,
      basic_price: "12.00",
      final_price: "8.99",
      discount_amount: "3.01",
      discount_percent: null,
    },
    vwItem: {
      item_id: 3599,
      type: "variant",
      track_inventory: false,
      available_qty: 10,
      reserved_qty: 0,
      product_id: 165,
      variant_id: 1251,
      custom_item_id: null,
      status: "published",
      deleted_at: null,
      product: {
        product_id: 165,
        sku: "iphone-case-explorer-wanted",
        has_variants: true,
        title: "Case Explorer wanted",
        url_key: "chekhol-explorer-wanted",
        default_category_id: 103,
        manufacturer_id: 34,
        tax_status: "taxable",
        tax_class_id: null,
      },
      variant: {
        variant_id: 1251,
        sku: "iphone-case-explorer-wanted-iPhone 5/5s",
        title: "iPhone 5/5s",
        cases: [615],
        size: [],
      },
      commodity_group: {
        group_id: 61,
        physical_products: true,
        title: "Default Product type",
        trackInventory: false,
      },
      image: {
        path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        width: 1501,
        height: 1501,
      },
      prices: [
        {
          point_id: 1,
          price_id: 7,
          alias: "selling_price",
          currency_id: 4,
          currency_alias: "usd",
          value: 8.99,
          min: null,
          max: null,
          is_auto_generated: true,
          old: 12,
          old_min: null,
          old_max: null,
        },
      ],
      labels: [
        {
          label_id: 4,
          color: "#0e8a16",
          text_color: "#000000",
          icon: null,
          remove_after: null,
          created_at: "2017-04-24 08:57:58.125999-04",
          deleted_at: null,
          title: "Best choice",
        },
      ],
    },
  },
];

export const filterRange: IFilterFieldsRangesResponse = {
  ranges: [
    {
      type: "price",
      range: {
        min: "7.00",
        max: "900.00",
        finalPrices: [],
      },
    },
  ],
  totalProducts: 16,
};

export const categoryParent: ICategoryFlatItem[] = [
  {
    category_id: 99,
    parent_id: null,
    lang_id: 1,
    title: "iPhone cases",
    url_key: "chekhly-na-iphone",
    tree_sort: "00000000",
    level: 0,
    deleted_at: null,
    custom_link: null,
    status: "published",
    image_id: null,
  },
];

export const cartOrder: IOrder = {
  id: "949b54ab-94d5-4231-af84-33a5e65ecbd9",
  service_total_price: "4.90",
  payment_mark_up: "0.00",
  total_price: "13.89",
  discount_for_order: "0.00",
  tax_amount: null,
  paid_at: null,
  status: null,
  customer: {
    id: "76cfe94f-4548-4908-8e16-bac298f8a505",
    email: "hr@yopmail.com",
    created_at: "2025-01-21 04:02:26.684286-05",
    first_name: "asd",
    last_name: "asd",
    phone: null,
    receive_marketing_info: true,
    custom_attrs: null,
    addresses: [
      {
        id: "51d32863-733c-4296-83ee-4a5110ffd73a",
        type: "shipping",
        is_default: true,
        first_name: "asd",
        last_name: "asd",
        company: "asd",
        address_line_1: "asd",
        address_line_2: null,
        city: "asd",
        state: "asdasd",
        country_id: 22,
        zip: "123",
        phone: "123123",
        created_at: "2025-01-21 04:02:49.03751-05",
        vwCountry: {
          country_id: 22,
          code: "be",
          title: "Belgium",
        },
      },
      {
        id: "4d61e569-b281-466c-88da-2ec3418ed4bd",
        type: "billing",
        is_default: false,
        first_name: "asd",
        last_name: "asd",
        company: "asd",
        address_line_1: "asd",
        address_line_2: null,
        city: "asd",
        state: "asdasd",
        country_id: 22,
        zip: "123",
        phone: "123123",
        created_at: "2025-01-21 04:02:49.07075-05",
        vwCountry: {
          country_id: 22,
          code: "be",
          title: "Belgium",
        },
      },
    ],
  },
  discounts: [],
  paymentMethod: null,
  services: [
    {
      order_service_id: 549,
      service_id: null,
      qty: 1,
      total_price: "4.90",
      item_price_id: 4141,
      is_delivery: true,
      serviceDelivery: {
        delivery_id: 23,
        title: null,
        text_info: null,
        data: null,
        delivery: {
          delivery_id: 23,
          title: "US Shipping",
          description: "Fast shipping in 2-days. Promise!",
          alias: null,
          img: null,
          shipping_id: null,
          shipping_config: {
            price: 4.9,
          },
          free_shipping_from: null,
          calc_method: "single",
          created_at: "2022-04-09 10:37:45.21814-04",
          shipping: null,
        },
      },
    },
  ],
  client_comment: null,
  custom_attrs: null,
  tax_calculations: {
    itemsSubTotal: {
      price: 8.99,
      qty: 1,
    },
    price: "13.89",
    discount: "0",
    paymentMarkup: "0",
    tax: {
      totalTaxAmount: null,
      itemsWithTax: [
        {
          id: 3596,
          price: "8.99",
          qty: 1,
          taxStatus: "taxable",
          taxClassId: null,
          taxBase: "8.990000",
        },
      ],
      mode: null,
    },
    servicesSubTotal: {
      price: 4.9,
      qty: 1,
    },
  },
  publishing_status: "draft",
  created_at: "2025-01-21 01:27:05.78328-05",
};

export const detailedCartOrder: IDetailedOrder = {
  ...cartOrder,
  order_id: 2165,
  items: [
    {
      reserve_item_id: 995,
      reserve_id: 523,
      stock_id: null,
      item_id: 3596,
      qty: 3,
      total_price: "26.97",
      item_price_id: 4150,
      created_at: "2025-01-22 03:41:40.967012-05",
      completed_at: null,
      itemPrice: {
        item_price_id: 4150,
        price_id: 7,
        basic_price: "12.00",
        final_price: "8.99",
        discount_amount: "3.01",
        discount_percent: null,
      },
      vwItem: {
        item_id: 3596,
        type: "variant",
        track_inventory: false,
        available_qty: 1,
        reserved_qty: 5,
        product_id: 165,
        variant_id: 1248,
        custom_item_id: null,
        status: "published",
        deleted_at: null,
        product: {
          product_id: 165,
          sku: "iphone-case-explorer-wanted",
          has_variants: true,
          title: "Case Explorer wanted",
          url_key: "chekhol-explorer-wanted",
          default_category_id: 103,
          manufacturer_id: 34,
          tax_status: "taxable",
          tax_class_id: null,
        },
        variant: {
          variant_id: 1248,
          sku: "iphone-case-explorer-wanted-iPhone 7",
          title: "iPhone 7",
          cases: [612],
          size: [],
        },
        commodity_group: {
          group_id: 61,
          physical_products: true,
          title: "Default Product type",
          trackInventory: false,
        },
        image: {
          path: "https://images.unsplash.com/photo-1736617004818-a01c44c494ee?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          width: 1501,
          height: 1501,
        },
        prices: [
          {
            point_id: 1,
            price_id: 7,
            alias: "selling_price",
            currency_id: 4,
            currency_alias: "usd",
            value: 8.99,
            min: null,
            max: null,
            is_auto_generated: true,
            old: 12,
            old_min: null,
            old_max: null,
          },
        ],
        labels: [
          {
            label_id: 4,
            color: "#0e8a16",
            text_color: "#000000",
            icon: null,
            remove_after: null,
            created_at: "2017-04-24 08:57:58.125999-04",
            deleted_at: null,
            title: "Best choice",
          },
        ],
      },
    },
  ],
  discounts: [],
  customer: {
    id: "870e26ca-78bd-4d97-b93c-64d9ecd925c8",
    email: "juanfrederick@yopmail.com",
    created_at: "2025-01-22 02:34:05.545114-05",
    first_name: "asda",
    last_name: "adsda",
    phone: null,
    receive_marketing_info: true,
    custom_attrs: null,
    addresses: [
      {
        id: "457c9f72-4a17-488f-a0a8-58e467c68186",
        type: "billing",
        is_default: true,
        first_name: "asda",
        last_name: "adsda",
        company: "sda",
        address_line_1: "sdas",
        address_line_2: null,
        city: "asdas",
        state: "asdasd",
        country_id: 17,
        zip: "dasd",
        phone: null,
        created_at: "2025-01-22 03:41:35.552814-05",
        vwCountry: {
          country_id: 17,
          code: "bs",
          title: "Bahamas",
        },
      },
    ],
  },
  status: {
    status_id: 9,
    alias: "new",
    title: "New",
    background_color: "C0605E",
    stock_location: "inside",
    sort: 0,
    created_at: "2015-09-02 00:44:24.632104-04",
    deleted_at: null,
  },
  paymentMethod: {
    payment_method_id: 1,
    title: "Cash on delivery",
    for_all_delivery: true,
    mark_up: "0.000",
    sort: 10,
    gateway_alias: "cashOnDelivery",
  },
  services: [
    {
      order_service_id: 554,
      service_id: null,
      qty: 1,
      total_price: "0.00",
      item_price_id: 4151,
      is_delivery: true,
      serviceDelivery: {
        delivery_id: 20,
        title: null,
        text_info: null,
        data: null,
        delivery: {
          delivery_id: 20,
          title: "Self-pickup from the store",
          description: null,
          alias: null,
          img: null,
          shipping_id: 2,
          shipping_config: {
            address:
              "1 infinite loop, <br>Cupertino, CA 95014 <br>9:00am &mdash; 6:00pm",
          },
          free_shipping_from: null,
          calc_method: "byShippingService",
          created_at: "2016-07-13 11:56:36.032345-04",
          shipping: {
            shipping_id: 2,
            shipping_title: "Self pickup",
            alias: "selfPickup",
            settings: null,
          },
        },
      },
    },
  ],
};

export const cartCheckoutTotalDummy: ITotal = {
  itemsSubTotal: {
    price: 23.98,
    qty: 2,
  },
  price: "28.88",
  discount: "0",
  paymentMarkup: "0",
  tax: {
    totalTaxAmount: null,
    itemsWithTax: [
      {
        id: 3596,
        price: "8.99",
        qty: 1,
        taxStatus: "taxable",
        taxClassId: null,
        taxBase: "8.990000",
      },
      {
        id: 3628,
        price: "14.99",
        qty: 1,
        taxStatus: "taxable",
        taxClassId: null,
        taxBase: "14.990000",
      },
    ],
    mode: null,
  },
  taxSettings: {
    turnedOn: false,
    pricesEnteredWithTax: false,
    calculateTaxBasedOn: "storeLocation",
    taxTitle: "Tax",
  },
  servicesSubTotal: {
    price: 4.9,
    qty: 1,
  },
  calcByAPI: true,
};

export const taxSettingsDummy: ISystemTax = {
  turnedOn: false,
  pricesEnteredWithTax: true,
  calculateTaxBasedOn: TCalculateTaxBasedOn.customerBillingAddress,
  taxTitle: "none",
};

export const stepperDummy: ICheckoutStepper = {
  steps: ["contact-info", "shipping-address", "payment-method"],
  filledSteps: ["contact-info", "shipping-address"],
  currentStep: "contact-info",
};

export const checkoutPageSettings: ICheckoutPageSettings = {
  contactFields: {
    phone: {
      show: false,
      required: false,
    },
    email: {
      show: true,
      required: true,
    },
  },
  logo: null,
  accountPolicy: "guest-and-login",
  customerNameRequired: ["last"],
  addressLine2: "hidden",
  companyName: "optional",
  footerLinks: [
    {
      title: "Refund policy",
      url: "/page/refund-policy",
    },
    {
      title: "Privacy policy",
      url: "/page/privacy-policy",
    },
    {
      title: "Terms of service",
      url: "/page/terms-of-service",
    },
  ],
};

export const checkoutShippingDummy: ICheckoutShippingPageData = {
  shippingAddress: null,
  billingAddress: null,
  orderServiceDelivery: null,
  person: {
    id: "06550b5f-104a-4520-9038-a7bb3c8fa1b0",
    email: "juanfrederick@yopmail.com",
    created_at: "2025-01-21 08:49:11.56456-05",
    first_name: null,
    last_name: null,
    phone: null,
    receive_marketing_info: true,
    custom_attrs: null,
    addresses: [],
    groups: [],
  },
  options: {
    delivery: [
      {
        delivery_id: 20,
        title: "Self-pickup from the store",
        description: null,
        alias: null,
        img: null,
        shipping_id: 2,
        shipping_config: {
          address:
            "1 infinite loop, <br>Cupertino, CA 95014 <br>9:00am &mdash; 6:00pm",
        },
        free_shipping_from: null,
        calc_method: "byShippingService",
        created_at: "2016-07-13 11:56:36.032345-04",
        shipping: {
          shipping_id: 2,
          shipping_title: "Self pickup",
          alias: "selfPickup",
          settings: null,
        },
      },
      {
        delivery_id: 23,
        title: "US Shipping",
        description: "Fast shipping in 2-days. Promise!",
        alias: null,
        img: null,
        shipping_id: null,
        shipping_config: {
          price: 4.9,
        },
        free_shipping_from: null,
        calc_method: "single",
        created_at: "2022-04-09 10:37:45.21814-04",
        shipping: null,
      },
      {
        delivery_id: 24,
        title: "Worldwide shipping",
        description: "Your order will be fulfilled and sent to USPS in 1 day.",
        alias: null,
        img: null,
        shipping_id: null,
        shipping_config: {
          price: 9.9,
        },
        free_shipping_from: null,
        calc_method: "single",
        created_at: "2022-04-09 10:38:23.923214-04",
        shipping: null,
      },
    ],
    country: [
      {
        country_id: 1,
        code: "af",
        title: "Afghanistan",
      },
      {
        country_id: 3,
        code: "al",
        title: "Albania",
      },
      {
        country_id: 4,
        code: "dz",
        title: "Algeria",
      },
      {
        country_id: 5,
        code: "as",
        title: "American Samoa",
      },
    ],
  },
};

export const paymentDataDummy: ICheckoutPaymentPageData = {
  paymentMethods: [
    {
      payment_method_id: 1,
      title: "Cash on delivery",
      for_all_delivery: true,
      mark_up: "0.000",
      sort: 10,
      gateway_alias: "cashOnDelivery",
    },
  ],
  billingAddress: {
    id: "27459306-11ca-412b-a167-a20d0f0f1aaf",
    type: "billing",
    is_default: true,
    first_name: "asd",
    last_name: "asdasd",
    company: "asasd",
    address_line_1: "asda",
    address_line_2: null,
    city: "asda",
    state: "sdasd",
    country_id: 6,
    zip: "sdasd",
    phone: null,
    created_at: "2025-01-22 02:20:50.216121-05",
    vwCountry: {
      country_id: 6,
      code: "ad",
      title: "Andorra",
    },
  },
  countries: [
    {
      country_id: 1,
      code: "af",
      title: "Afghanistan",
    },
    {
      country_id: 3,
      code: "al",
      title: "Albania",
    },
    {
      country_id: 4,
      code: "dz",
      title: "Algeria",
    },
    {
      country_id: 5,
      code: "as",
      title: "American Samoa",
    },
  ],
};
